name: "Coding paradigm: line by line"
title: "Coding paradigm: line by line"
tagline: "Personal blog and opinions by Leonids Maslovs"
description: "Personal blog and opinions by Leonids Maslovs"
author:
  name: "Leonids Maslovs"
  email: "leonids.maslovs@galeoconsulting.com"
baseurl: ''
url: http://leonardinius.galeoconsulting.com
permalink: /:year/:month/:title
markdown: redcarpet
redcarpet:
    extensions: [with_toc_data] 
highlighter: pygments
paginate: 5

exclude:
  - CNAME
  - LICENSE
  - README.md
  - local.sh
  - Vagrantfile

gems:
  - jekyll-sitemap

github:
  repo: "https://github.com/leonardinius/leonardinius.github.io"
  branch: "master"

analytics:
  provider: "google"
  google:
    code: "UA-3088662-1"

comments:
  provider: "disqus"
  disqus:
    code: 'codingparadigmlinebyline'
