env: "DEV"

name: "Coding paradigm: line by line"
title: "Coding paradigm: line by line"
tagline: "all my opinions are belong to me"
description: "Personal blog and opinions by Leonids Maslovs"
author:
  name: "Leonids Maslovs"
  twitter: "leonardinius"
  email: "leonids.maslovs@galeoconsulting.com"
baseurl: '/'
url: http://leonardinius.galeoconsulting.com/
permalink: /:year/:month/:title
markdown: kramdown
paginate: 5

gems:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - CNAME
  - LICENSE
  - README.md
  - run.sh

github:
  repo: "https://github.com/leonardinius/leonardinius.github.io"
  branch: "master"

analytics:
  provider: "none"

comments:
  provider: "none"
