name: "Coding paradigm: line by line"
title: "Coding paradigm: line by line"
tagline: "Personal blog and opinions by Leonids Maslovs"
description: "Personal blog and opinions by Leonids Maslovs"
author:
  name:       "Leonids Maslovs"
  email:      "leonids.maslovs@galeoconsulting.com"
baseurl: ''
url: http://leonardinius.galeoconsulting.com
permalink: /:year/:month/:title
markdown: redcarpet
pygments: true
paginate: 5
